// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller users

import {revokeAdmin} from '../../../controllers/users.js'

export function del(req, res) {
    return revokeAdmin(req, res)
}


