// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller autotests

import {useAndConnectDevice} from '../../controllers/autotests.js'

export function post(req, res) {
    return useAndConnectDevice(req, res)
}


