services:
  adbd:
    container_name: adbd
    image: "devicefarmer/adb:latest"
    restart: unless-stopped
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    healthcheck:
      test: nc -vz 192.168.0.102 5037
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    network_mode: host
  devicehub-mongo:
    image: mongo:7.0
    hostname: devicehub-mongo
    container_name: devicehub-mongo
    ports:
      - 27017:27017
    entrypoint: ["mongod", "--replSet", "devicehub-rs", "--bind_ip_all"]
    healthcheck:
      test: echo "rs.status()" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    restart: unless-stopped
    network_mode: host
    volumes:
      - devicehub-db-volume:/data/db
  devicehub-mongosetup:
    image: mongo:7.0
    container_name: devicehub-mongosetup
    depends_on:
      devicehub-mongo:
        condition: service_healthy
    volumes:
      - ./scripts/mongo_setup.sh:/scripts/mongo_setup.sh
    restart: "no"
    entrypoint: ["bash", "/scripts/mongo_setup.sh"]
    network_mode: host
  devicehub-migrate:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-migrate
    env_file:
      - scripts/variables.env
    command: stf migrate
    depends_on:
      devicehub-mongosetup:
        condition: service_completed_successfully
    network_mode: host
  devicehub-app:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-app
    env_file:
      - scripts/variables.env
    command: stf app --port 3100 --auth-url https://${STF_DOMAIN}:${STF_PORT}/${AUTH_URL} --websocket-url https://${STF_DOMAIN}:${STF_PORT}/ --secret=${STF_SECRET}
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-auth:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-auth
    env_file:
      - scripts/variables.env
    command: stf auth-ldap --port 3200 --app-url https://${STF_DOMAIN}:${STF_PORT} --secret=${STF_SECRET}
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-processor:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-processor
    env_file:
      - scripts/variables.env
    command: stf processor --name processor --connect-app-dealer tcp://devicehub-triproxy-app:7160 --connect-dev-dealer tcp://devicehub-triproxy-dev:7260 --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --connect-sub-dev tcp://devicehub-triproxy-dev:7250 --connect-push-dev tcp://devicehub-triproxy-dev:7270
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-reaper:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-reaper
    env_file:
      - scripts/variables.env
    command: stf reaper --name reaper001 --connect-push tcp://devicehub-triproxy-dev:7270 --connect-sub tcp://devicehub-triproxy-app:7150 --heartbeat-timeout 30000
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-storage-plugin-apk:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-storage-plugin-apk
    env_file:
      - scripts/variables.env
    command: stf storage-plugin-apk --port 3300 --storage-url http://devicehub-storage-temp/ --secret=${STF_SECRET}
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-storage-plugin-image:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-storage-plugin-image
    env_file:
      - scripts/variables.env
    command: stf storage-plugin-image --port 3400 --storage-url https://${STF_DOMAIN}:${STF_PORT}/ --secret=${STF_SECRET}
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-storage-temp:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-storage-temp
    env_file:
      - scripts/variables.env
    command: stf storage-temp --port 3500 --save-dir /tmp --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --secret=${STF_SECRET}
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-triproxy-app:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-triproxy-app
    env_file:
      - scripts/variables.env
    command: stf triproxy app001 --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
#    ports:
#      - "7150:7150"
#      - "7160:7160"
#      - "7170:7170"
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-triproxy-dev:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-triproxy-dev
    env_file:
      - scripts/variables.env
    command: stf triproxy --name dev001 --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
#    ports:
#      - "7250:7250"
#      - "7260:7260"
#      - "7270:7270"
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-websocket:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-websocket
    env_file:
      - scripts/variables.env
    command: stf websocket --port 3600 --storage-url https://${STF_DOMAIN}:${STF_PORT}/ --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --connect-sub-dev tcp://devicehub-triproxy-dev:7250 --connect-push-dev tcp://devicehub-triproxy-dev:7270 --secret=${STF_SECRET}
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-api:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-api
    env_file:
      - scripts/variables.env
    command: stf api --port 3700 --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --connect-sub-dev tcp://devicehub-triproxy-dev:7250 --connect-push-dev tcp://devicehub-triproxy-dev:7270 --secret=${STF_SECRET}
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-api-groups-engine:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-api-groups-engine
    env_file:
      - scripts/variables.env
    command: stf groups-engine --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --connect-sub-dev tcp://devicehub-triproxy-dev:7250 --connect-push-dev tcp://devicehub-triproxy-dev:7270
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    network_mode: host
  devicehub-provider:
    build: .
    image: vkcom/devicehub
    container_name: devicehub-provider
    env_file:
      - scripts/variables.env
#    ports:
#      - "12010-12100:12010-12100"
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
      adbd:
        condition: service_healthy
    restart: unless-stopped
    command: stf provider --name devicehub-provider --adb-host adbd --no-cleanup --connect-sub tcp://devicehub-triproxy-dev:7250 --connect-push tcp://devicehub-triproxy-dev:7270 --storage-url https://${STF_DOMAIN}:${STF_PORT}/ --public-ip ${STF_DOMAIN} --min-port=12010 --max-port=12100 --heartbeat-interval 10000 --screen-ws-url-pattern "wss://${STF_DOMAIN}:${STF_PORT}/d/devicehub-provider/<%= publicPort %>/" --secret=${STF_SECRET}
    network_mode: host
volumes:
  devicehub-db-volume:
