export const OPENSTF_API_ROUTES = {
  devices: '/devices',
  groups: '/groups',
  users: '/users',
  user: '/user',
  accessTokens: '/user/accessTokens',
  accessTokenByTitle: '/user/accessTokens/byTitle',
  adbRange: '/devices/adbRange',
  defaultGroupsQuotas: '/users/groupsQuotas',
  alertMessage: '/users/alertMessage',
  groupUser: (id: string, email?: string) => (email ? `/groups/${id}/users/${email}` : `/groups/${id}/users`),
  groupDevice: (id: string, serial?: string) => (serial ? `/groups/${id}/devices/${serial}` : `/groups/${id}/devices`),
  deviceGroup: (id: string, serial?: string) => (serial ? `/devices/${serial}/groups/${id}` : `/devices/groups/${id}`),
  updateStorageInfo: (serial: string) => `/devices/${serial}/updateStorageInfo`,
  adbPort: (serial: string) => `/devices/${serial}/adbPort`,
  userGroupQuota: (email: string) => `/users/${email}/groupsQuotas`,
  grantAdmin: (email: string) => `/users/grantAdmin/${email}`,
  revokeAdmin: (email: string) => `/users/revokeAdmin/${email}`,
  accessTokensByEmail: (email: string) => `/users/${email}/accessTokens`,
  groupModerator: (id: string, email: string) => `/groups/${id}/moderators/${email}`,
} as const
