import { DeviceTableColumnIds } from './types'

export const ROW_HEIGHT = 80

export const COLUMN_VISIBILITY_DEFAULT: Record<DeviceTableColumnIds, boolean> = {
  abi: false,
  batteryHealth: false,
  batteryLevel: false,
  batterySource: false,
  batteryStatus: false,
  batteryTemp: false,
  bookedBefore: true,
  browser: true,
  cpuPlatform: false,
  groupClass: false,
  groupExpirationDate: false,
  groupName: false,
  groupOrigin: false,
  groupOwner: false,
  groupStartingDate: false,
  macAddress: false,
  manufacturer: false,
  marketName: true,
  mobileService: true,
  model: false,
  network: false,
  notes: true,
  openGLESVersion: false,
  operator: false,
  ownerName: false,
  phone: false,
  phoneIccid: false,
  phoneImei: false,
  phoneImsi: false,
  place: false,
  platform: false,
  product: true,
  providerName: false,
  released: false,
  repetitions: false,
  screen: false,
  sdk: true,
  serial: false,
  state: true,
  storageId: false,
  version: true,
}

export const DEFAULT_COLUMN_ORDER: DeviceTableColumnIds[] = [
  DeviceTableColumnIds.STATE,
  DeviceTableColumnIds.MODEL,
  DeviceTableColumnIds.PRODUCT,
  DeviceTableColumnIds.PLATFORM,
  DeviceTableColumnIds.SERIAL,
  DeviceTableColumnIds.OPERATOR,
  DeviceTableColumnIds.RELEASED,
  DeviceTableColumnIds.VERSION,
  DeviceTableColumnIds.NETWORK,
  DeviceTableColumnIds.SCREEN,
  DeviceTableColumnIds.MANUFACTURER,
  DeviceTableColumnIds.MARKET_NAME,
  DeviceTableColumnIds.SDK,
  DeviceTableColumnIds.ABI,
  DeviceTableColumnIds.CPU_PLATFORM,
  DeviceTableColumnIds.OPEN_GL_ES_VERSION,
  DeviceTableColumnIds.BROWSER,
  DeviceTableColumnIds.MOBILE_SERVICE,
  DeviceTableColumnIds.MAC_ADDRESS,
  DeviceTableColumnIds.PLACE,
  DeviceTableColumnIds.STORAGE_ID,
  DeviceTableColumnIds.PHONE,
  DeviceTableColumnIds.PHONE_IMEI,
  DeviceTableColumnIds.PHONE_IMSI,
  DeviceTableColumnIds.PHONE_ICCID,
  DeviceTableColumnIds.BATTERY_HEALTH,
  DeviceTableColumnIds.BATTERY_SOURCE,
  DeviceTableColumnIds.BATTERY_STATUS,
  DeviceTableColumnIds.BATTERY_LEVEL,
  DeviceTableColumnIds.BATTERY_TEMP,
  DeviceTableColumnIds.PROVIDER_NAME,
  DeviceTableColumnIds.NOTES,
  DeviceTableColumnIds.OWNER_NAME,
  DeviceTableColumnIds.GROUP_NAME,
  DeviceTableColumnIds.GROUP_CLASS,
  DeviceTableColumnIds.GROUP_STARTING_DATE,
  DeviceTableColumnIds.GROUP_EXPIRATION_DATE,
  DeviceTableColumnIds.REPETITIONS,
  DeviceTableColumnIds.GROUP_OWNER,
  DeviceTableColumnIds.GROUP_ORIGIN,
  DeviceTableColumnIds.BOOKED_BEFORE,
]
