// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller users

import {getUserAccessTokensV2, createUserAccessToken, deleteUserAccessTokens} from '../../../controllers/users.js'

export function get(req, res) {
    return getUserAccessTokensV2(req, res)
}


export function post(req, res) {
    return createUserAccessToken(req, res)
}


export function del(req, res) {
    return deleteUserAccessTokens(req, res)
}


