// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller users

import {getUserDevicesV2} from '../../../controllers/users.js'

export function get(req, res) {
    return getUserDevicesV2(req, res)
}


