// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller autotests

import {addDevices} from '../../../controllers/autotests.js'

export function get(req, res) {
    return addDevices(req, res)
}


