// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller stats

import {writeStats} from '../controllers/stats.js'

export function post(req, res) {
    return writeStats(req, res)
}


