// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller user

import {getUser} from '../controllers/user.js'

export function get(req, res) {
    return getUser(req, res)
}


