export enum GroupDevicesColumnIds {
  IS_IN_GROUP = 'isInGroup',
  MODEL = 'model',
  SERIAL = 'serial',
  CARRIER = 'carrier',
  OS = 'os',
  NETWORK = 'network',
  SCREEN = 'screen',
  MANUFACTURER = 'manufacturer',
  SDK = 'sdk',
  ABI = 'abi',
  CPU_PLATFORM = 'cpuPlatform',
  OPEN_GLES_VERSION = 'openGLESVersion',
  MARKET_NAME = 'marketName',
  PHONE_IMEI = 'phoneIMEI',
  LOCATION = 'location',
  GROUP_ORIGIN = 'groupOrigin',
}
