// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller users

import {updateDefaultUserGroupsQuotas} from '../../controllers/users.js'

export function put(req, res) {
    return updateDefaultUserGroupsQuotas(req, res)
}


