// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller users

import {createServiceUser} from '../../../controllers/users.js'

export function post(req, res) {
    return createServiceUser(req, res)
}


