// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller user

import {getAccessTokenByTitle} from '../../../controllers/user.js'

export function post(req, res) {
    return getAccessTokenByTitle(req, res)
}


