// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller devices

import {updateStorageInfo} from '../../../controllers/devices.js'

export function put(req, res) {
    return updateStorageInfo(req, res)
}


