// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller devices

import {useDeviceByUser} from '../../../controllers/devices.js'

export function post(req, res) {
    return useDeviceByUser(req, res)
}


