// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller user

import {getUserDevices, addUserDevice} from '../../controllers/user.js'

export function get(req, res) {
    return getUserDevices(req, res)
}


export function post(req, res) {
    return addUserDevice(req, res)
}


