// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller devices

import {generateFakeDevice} from '../../controllers/devices.js'

export function get(req, res) {
    return generateFakeDevice(req, res)
}


